// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";

/** Commands */
export const commands = {
	/**  首个贯通 Rust → TS 的命令。 */
	appInfo: () => __TAURI_INVOKE<AppInfo>("app_info"),
};

/* Types */
/**  应用与运行时的基础信息。 */
export type AppInfo = {
	/**  产品名。 */
	name: string,
	/**  应用版本（单一来源 = 根 package.json）。 */
	version: string,
	/**  运行平台（`std::env::consts::OS`）。 */
	os: string,
};

